name: Update Files from URLs

on:
  workflow_dispatch:  # 👈 This allows you to trigger it manually
  schedule:
    - cron: '0 * * * *'  # 👈 Still keeps your hourly cron job

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 update_files.py


